blank_issues_enabled: false
contact_links:
  - name: Meshtastic Public Beta Test Flight  Link
    url: https://testflight.apple.com/join/c8nNl8q1
    about: Please submit any bugs through TestFlight, bugs submitted as GitHub issues will be closed.
